# Test environment overrides
name: example-app

image:
  tag: test

replicaCount: 1

env:
  ENVIRONMENT: test

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi
